dist: trusty
language: cpp

os:
  - linux

install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      lsb_release -a
      sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-add-repository -y ppa:beineri/opt-qt562-trusty
      sudo apt-get -qq update
      sudo apt-get -qq install g++-4.8 libc6-i386 qt56tools qt56svg qt56script
      export CXX="g++-4.8"
      export CC="gcc-4.8"
    fi

script:
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      QTDIR="/opt/qt56"
      PATH="$QTDIR/bin:$PATH"
      qt56-env.sh
    fi
  - mkdir build && cd build
  - cmake ..
  - make
